### ISSUE TITLE
Uploading an image using a multipart request with OAuth2 access token

### ISSUE THREAD

**Issue by shivrams** [idan/oauthlib#327]
I'm having trouble uploading an image using a multipart/form-data request. Traceback is below, I'm using oauthlib 0.6.1
```
Traceback (most recent call last):
  File "*******oauth_validators.py", line 30, in validate
    server.verify_request(uri, method, body, headers, scopes)
  File "/usr/local/lib/python2.7/dist-packages/oauthlib/oauth2/rfc6749/endpoints/base.py", line 61, in wrapper
    return f(endpoint, uri, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/oauthlib/oauth2/rfc6749/endpoints/resource.py", line 62, in verify_request
    request = Request(uri, http_method, body, headers)
  File "/usr/local/lib/python2.7/dist-packages/oauthlib/common.py", line 359, in __init__
    self.body = encode(body)
  File "/usr/local/lib/python2.7/dist-packages/oauthlib/common.py", line 354, in <lambda>
    encode = lambda x: to_unicode(x, encoding) if encoding else x
  File "/usr/local/lib/python2.7/dist-packages/oauthlib/common.py", line 288, in to_unicode
    return unicode_type(data, encoding=encoding)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xff in position 613: invalid start byte
```

It seems that as part of request verification, oauthlib expects the body byte string to be encoded in utf-8. Since the image's raw bytes are present in the multipart/form-data body, converting the body to unicode raises the UnicodeDecodeError.

I may be understanding this incorrectly, but is there no way to upload the image as raw bytes instead of base64 encoding the image?

**Comment by ThiefMaster** [comment]
https://github.com/idan/oauthlib/blob/master/oauthlib/oauth2/rfc6749/tokens.py#L196 is probably the culprit. The file uses `unicode_literals`, but headers should be bytes, not unicode.

In my case (with Flask-OAuthlib) I simply subclassed `OAuthRemoteApp` and fixed it in `http_request`:

```
    @staticmethod
    def http_request(uri, headers=None, data=None, method=None):
        # WTF. the oauth2 lib adds the token header as unicode, which
        # breaks if the body is bytes (e.g. binary image data)
        if headers:
            headers = {k.encode('utf-8'): v.encode('utf-8') for k, v in headers.iteritems()}
        return super(FixedOAuthRemoteApp, FixedOAuthRemoteApp).http_request(uri, headers, data, method)
```

If you use oauthlib directly you'll probably need to add similar code somewhere else

**Comment by rcmachado** [comment]
This problem is still happening in the latest version (2.0.6).

What would be the ideal solution? Not try to convert the body to unicode at all (but I imagine that this could break the backwards compatibility)?

cc @ib-lundgren (sorry, not sure who is the best one to answer this).

**Comment by scyclops** [comment]
I'm also running into this problem as described by @shivrams with oauthlib 2.0.6

**Comment by JonathanHuot** [comment]
Hi everyone,
Would it be possible to add more details on how to reproduce it ? Doing a small testcase would be ideal, else, even pseudo code would be great.
Also, while @ThiefMaster mentionned Flask-OAuthlib, we don't know about the others. Is it with requests-oauthlib, with OAuth1.0 server, with OAuth2.0, .. Any details are welcomed.

**Comment by scyclops** [comment]
The code below should reproduce the bug using web.py and Python 2.7.  Once the server and client code are run, the stacktrace should be printed to stdout on the console where the server is running.

**Server**
```python

import web # pip install web.py==0.38
from oauthlib.oauth2 import WebApplicationServer, RequestValidator

class DummyValidator(RequestValidator):
    def validate_bearer_token(self, *args, **kwargs):
        return True

SERVER = WebApplicationServer(DummyValidator())

class View(object):
    def GET(self):

        uri, http_method, body, headers = (
            web.ctx.fullpath, web.ctx.method, web.data(), web.ctx.headers
        )
        scopes = []

        valid, request = SERVER.verify_request(
            uri, http_method, body, headers, scopes
        )

        return 'success'

    def POST(self):
        return self.GET()

        
if __name__ == "__main__":
    web.application(('/', View)).run()
```

**Client**
```python
import requests

blank_gif_data = (
    'GIF89a\x01\x00\x01\x00\x80\x00\x00\xff\xff\xff\xff\xff\xff!\xf9'
    '\x04\x01\n\x00\x01\x00,\x00\x00\x00\x00\x01\x00\x01\x00\x00\x02'
    '\x02L\x01\x00;'
)

r = requests.post('http://localhost:8080/', files=dict(image=('blank.gif', blank_gif_data)))
r.raise_for_status()

print r
print r.content
```

**Comment by JonathanHuot** [comment]
Thanks for your test case !

We can cleary see a gap in the implementation and the RFC. We should read the `access_token` in the body *only if* : 

> (...)
>    o  The HTTP request entity-header includes the "Content-Type" header
>       field set to "application/x-www-form-urlencoded".
> (...)

See *section 2.2.  Form-Encoded Body Parameter* for all the details: https://tools.ietf.org/html/rfc6750#section-2.2

That's cleary a bug and it needs to be fixed.
