### ISSUE TITLE
encoding = request.encoding or 'utf-8' raises AttributeError: encoding

### ISSUE THREAD

**Issue by aidanlister** [idan/oauthlib#363]
Our pip freeze didn't have a specific version of oauthlib in it, so today our tests just started failing. It looks like the 1.0.0 release has this ```encoding = request.encoding or 'utf-8'``` in it which should perhaps be ```encoding = getattr(request, 'encoding', 'utf-8')```

Here's the traceback:
```
Traceback (most recent call last):
  File "/home/travis/build/ABASystems/abas-web/abas/apps/api/tests.py", line 134, in testAuthentication
    self.authorizeAPI()
  File "/home/travis/build/ABASystems/abas-web/abas/apps/api/tests.py", line 85, in authorizeAPI
    response = self.client.post('/api/oauth2/token/', data, **auth_headers)
  File "/home/travis/virtualenv/python3.4.2/lib/python3.4/site-packages/django/test/client.py", line 512, in post
    secure=secure, **extra)
  File "/home/travis/virtualenv/python3.4.2/lib/python3.4/site-packages/django/test/client.py", line 313, in post
    secure=secure, **extra)
  File "/home/travis/virtualenv/python3.4.2/lib/python3.4/site-packages/django/test/client.py", line 379, in generic
    return self.request(**r)
  File "/home/travis/virtualenv/python3.4.2/lib/python3.4/site-packages/django/test/client.py", line 466, in request
    six.reraise(*exc_info)
  File "/home/travis/virtualenv/python3.4.2/lib/python3.4/site-packages/django/utils/six.py", line 659, in reraise
    raise value
  File "/home/travis/virtualenv/python3.4.2/lib/python3.4/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/travis/virtualenv/python3.4.2/lib/python3.4/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/travis/virtualenv/python3.4.2/lib/python3.4/site-packages/django/utils/decorators.py", line 34, in _wrapper
    return bound_func(*args, **kwargs)
  File "/home/travis/virtualenv/python3.4.2/lib/python3.4/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/travis/virtualenv/python3.4.2/lib/python3.4/site-packages/django/utils/decorators.py", line 30, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/home/travis/virtualenv/python3.4.2/lib/python3.4/site-packages/braces/views/_forms.py", line 22, in dispatch
    return super(CsrfExemptMixin, self).dispatch(*args, **kwargs)
  File "/home/travis/virtualenv/python3.4.2/lib/python3.4/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/travis/virtualenv/python3.4.2/lib/python3.4/site-packages/django/utils/decorators.py", line 34, in _wrapper
    return bound_func(*args, **kwargs)
  File "/home/travis/virtualenv/python3.4.2/lib/python3.4/site-packages/django/views/decorators/debug.py", line 76, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
  File "/home/travis/virtualenv/python3.4.2/lib/python3.4/site-packages/django/utils/decorators.py", line 30, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/home/travis/virtualenv/python3.4.2/lib/python3.4/site-packages/oauth2_provider/views/base.py", line 170, in post
    url, headers, body, status = self.create_token_response(request)
  File "/home/travis/virtualenv/python3.4.2/lib/python3.4/site-packages/oauth2_provider/views/mixins.py", line 124, in create_token_response
    return core.create_token_response(request)
  File "/home/travis/virtualenv/python3.4.2/lib/python3.4/site-packages/oauth2_provider/oauth2_backends.py", line 106, in create_token_response
    headers)
  File "/home/travis/virtualenv/python3.4.2/lib/python3.4/site-packages/oauthlib/oauth2/rfc6749/endpoints/base.py", line 64, in wrapper
    return f(endpoint, uri, *args, **kwargs)
  File "/home/travis/virtualenv/python3.4.2/lib/python3.4/site-packages/oauthlib/oauth2/rfc6749/endpoints/token.py", line 100, in create_token_response
    request, self.default_token_type)
  File "/home/travis/virtualenv/python3.4.2/lib/python3.4/site-packages/oauthlib/oauth2/rfc6749/grant_types/resource_owner_password_credentials.py", line 101, in create_token_response
    if not self.request_validator.authenticate_client(request):
  File "/home/travis/virtualenv/python3.4.2/lib/python3.4/site-packages/oauth2_provider/oauth2_validators.py", line 166, in authenticate_client
    authenticated = self._authenticate_basic_auth(request)
  File "/home/travis/virtualenv/python3.4.2/lib/python3.4/site-packages/oauth2_provider/oauth2_validators.py", line 58, in _authenticate_basic_auth
    encoding = request.encoding or 'utf-8'
  File "/home/travis/virtualenv/python3.4.2/lib/python3.4/site-packages/oauthlib/common.py", line 409, in __getattr__
    raise AttributeError(name)
AttributeError: encoding
```

**Comment by masci** [comment]
This is an issue in Django OAuth Toolkit, unfortunately we haven't pinned oauthlib version in our requirements.
I've already the code to address this problem (along with other fixes) but I need a patch in oauthlib before merging, see #362.
Sorry for the inconvenience.

**Comment by masci** [comment]
Fixed in DOT v.0.9.0
