### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'headers'

### ISSUE THREAD

**Issue by coreycb** [idan/oauthlib#380]
This is on version oauthlib 1.0.0.

Traceback (most recent call last):
  File "keystoneclient/tests/unit/v3/test_oauth1.py", line 235, in test_create_access_token_expires_at
    oauth_client)
  File "keystoneclient/tests/unit/v3/test_oauth1.py", line 112, in _validate_oauth_headers
    header_params = oauth_client.get_oauth_params(None)
  File "/usr/lib/python2.7/dist-packages/oauthlib/oauth1/rfc5849/__init__.py", line 181, in get_oauth_params
    content_type = request.headers.get('Content-Type', None)
AttributeError: 'NoneType' object has no attribute 'headers'

Should get_oauth_params() be checking if request is None or is that a user error?

**Comment by jvanasco** [comment]
That looks like a user error to me.  `get_oauth_params` specifies 1 argument -- a request -- and you're explicitly sending in `None`.

**Comment by coreycb** [comment]
Fair enough, thanks for looking.
